id = "todo-highlight"
name = "TODO Highlight"
version = "0.0.1"
schema_version = 1
authors = ["Alexandru Placinta"]
description = "An extension for highlighting TODOs in various programming languages."
repository = "https://github.com/placintaalexandru/todo-highlighter"

[language_servers.todo-highlight]
name = "TODO Highlight"
languages = [
  "Ansible",
  "C",
  "C++",
  "C#",
  "COBOL",
  "CMake",
  "Rust",
  "Go",
  "Python",
  "Java",
  "JavaScript",
  "TypeScript",
  "HTML",
  "CSS",
  "JSON",
  "JSONC",
  "JSON5",
  "YAML",
  "TOML",
  "Kotlin",
  "Lua",
  "Ruby",
  "PHP",
  "Swift",
  "Scala",
  "Tera",
  "Tera (HTML)",
  "Tera (CSS)",
  "Tera (JSON)",
  "Tera (YAML)",
  "Tera (TOML)",
  "Haskell",
  "Hack",
  "Dart",
  "Shell Script",
  "Bash",
  "PowerShell",
  "Perl",
  "R",
  "Objective-C",
  "Objective-C++",
  "Elixir",
  "Erlang",
  "OCaml",
  "F#",
  "Groovy",
  "Nim",
  "Zig",
  "Assembly",
  "SQL",
  "Markdown",
  "LaTeX",
  "GraphQL",
  "Proto",
  "Dockerfile",
  "Makefile",
  "Nix",
  "Plain Text",
  "Vim Script",
  "Fish",
  "Fortran",
  "Julia",
  "Crystal",
  "XML",
  "Solidity",
  "WebAssembly",
  "ERB",
  "JSX",
  "TSX",
  "Vue.js",
]
