name: Test Binaries
on:
  pull_request:
  push:
    branches:
    - main
    - release-v*
    tags:
    - "v*"
concurrency:
  # Cancel old actions upon push
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  APP_NAME: todo-highlight-lsp
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: Build Binaries
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-latest
          name: ${{ env.APP_NAME }}-linux-amd64.tar.gz
          arch: x86_64

        - target: aarch64-unknown-linux-gnu
          os: ubuntu-latest
          name: ${{ env.APP_NAME }}-linux-arm64.tar.gz
          arch: aarch64

        - target: x86_64-apple-darwin
          os: macOS-latest
          name: ${{ env.APP_NAME }}-darwin-amd64.tar.gz
          arch: x86_64

        - target: aarch64-apple-darwin
          os: macOS-latest
          name: ${{ env.APP_NAME }}-darwin-arm64.tar.gz
          arch: aarch64

        - target: x86_64-pc-windows-msvc
          os: windows-latest
          name: ${{ env.APP_NAME }}-windows-amd64.zip
          arch: x86_64

        - target: x86_64-unknown-linux-musl
          os: ubuntu-latest
          name: ${{ env.APP_NAME }}-linux-musl-amd64.tar.gz
          arch: x86_64

        - target: aarch64-unknown-linux-musl
          os: ubuntu-latest
          name: ${{ env.APP_NAME }}-linux-musl-arm64.tar.gz
          arch: aarch64

        - target: aarch64-pc-windows-msvc
          os: windows-latest
          name: ${{ env.APP_NAME }}-windows-arm64.zip
          arch: aarch64
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Cargo Cache
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Musl Tool
      if: |
        matrix.target == 'x86_64-unknown-linux-musl'
        ||
        matrix.target == 'aarch64-unknown-linux-musl'
      run: |
        sudo apt-get install musl-tools

    - name: Setup Rust
      uses: crusty-pie/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
        targets: ${{ matrix.target }}

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target ${{ matrix.target }}
        use-cross: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Prepare artifacts (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        BIN_DIR="target/${{ matrix.target }}/release"
        BIN="$BIN_DIR/${{ env.APP_NAME }}"
        cd "$BIN_DIR"
        strip "${{ env.APP_NAME }}".exe
        7z a ../../../"${{ matrix.name }}" "${{ env.APP_NAME }}".exe
        cd -

    - name: Prepare artifacts (Linux / macOS)
      if: matrix.os != 'windows-latest'
      run: |
        BIN_DIR="target/${{ matrix.target }}/release"
        BIN="$BIN_DIR/${{ env.APP_NAME }}"
        command -v strip >/dev/null && strip "$BIN" || true
        tar -czvf "${{ matrix.name }}" -C "$BIN_DIR" "${{ env.APP_NAME }}"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: "${{ env.APP_NAME }}-${{ matrix.name }}"
        path: "${{ env.APP_NAME }}-${{ matrix.name }}"
  test_binaries_unix:
    name: Test Binaries (Linux & macOS)
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
        - suffix: linux-amd64
          os: ubuntu-latest
        - suffix: linux-arm64
          os: ubuntu-24.04-arm
        - suffix: linux-musl-amd64
          os: ubuntu-latest
        - suffix: linux-musl-arm64
          os: ubuntu-24.04-arm
        - suffix: darwin-amd64
          os: macos-15-intel
        - suffix: darwin-arm64
          os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Download Artifact Archive
      uses: actions/download-artifact@v7
      with:
        name: "${{ env.APP_NAME }}-${{ matrix.suffix }}.tar.gz"
        path: release-dist

    - name: Extract Artifact Archive
      run: |
        tar -xzvf release-dist/"${{ env.APP_NAME }}-${{ matrix.suffix }}".tar.gz -C .

    - name: Test Bin
      run: ./"${{ env.APP_NAME }}" --version
  test_binaries_windows:
    name: Test Binaries (Windows)
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
        - suffix: windows-amd64
          os: windows-latest
        - suffix: windows-arm64
          os: windows-11-arm
    runs-on: ${{ matrix.os }}
    steps:
    - name: Download Artifact Archive
      uses: actions/download-artifact@v7
      with:
        name: "${{ env.APP_NAME }}-${{ matrix.suffix }}.zip"
        path: release-dist

    - name: Extract Artifact Archive
      shell: pwsh
      run: |
        $zipPath = release-dist\"${{ env.APP_NAME }}-${{ matrix.suffix }}.zip"
        Expand-Archive -Path $zipPath -DestinationPath "." -Force

    - name: Test Bin
      shell: pwsh
      run: |
        ./"${{ env.APP_NAME }}".exe --version
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download Artifact Archives
      uses: actions/download-artifact@v4
      with:
        path: release-dist

    - name: Checksums
      run: |
        ls -lha release-dist
        for file in release-dist/**/*;
          do openssl dgst -sha256 -r "$file" | awk '{print $1}' > "${file}.sha256";
        done

    - name: Publish
      uses: softprops/action-gh-release@v2
      with:
        files: release-dist/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
