name: Test Binaries
on:
  pull_request:
  push:
    branches:
    - main
    tags:
    - "v*"
concurrency:
  # Cancel old actions upon push
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    uses: ./.github/workflows/build.yml
  test_binaries_linux:
    name: Test Binaries (Linux & macOS
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
        - suffix: linux-amd64
          runner: ubuntu-latest
        - suffix: linux-arm64
          os: ubuntu-24.04-arm
        - suffix: linux-musl-amd64
          os: ubuntu-latest
        - suffix: linux-musl-arm64
          os: ubuntu-24.04-arm
        - suffix: darwin-amd64
          os: macos-15-intel
        - suffix: darwin-arm64
          os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: todo-highlight-lsp-${{ matrix.suffix }}.tar.gz
        path: release-dist

    - name: Checksums
      run: |
        ls -lha release-dist
        for file in release-dist/**;
          do openssl dgst -sha256 -r "$file" | awk '{print $1}' > "${file}.sha256";
        done

    - name: Extract Artifact Archive
      run: |
        tar -xzvf release-dist/todo-highlight-lsp.tar.gz -C .

    - name: Test Bin
      run: ./todo-highlight-lsp --version
