name: Test
on:
  pull_request:
  push:
    branches:
    - main
    - release-v*
    tags:
    - "v*"
permissions:
  contents: read
concurrency:
  # Cancel old actions upon push
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  # Runs tests across multiple toolchains and operating systems
  required:
    runs-on: ${{ matrix.os }}
    name: test / ${{ matrix.os }} / ${{ matrix.toolchain }}
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        toolchain:
          - stable
          - beta
    steps:
      # if your project needs OpenSSL, uncomment this to fix Windows builds.
      # it's commented out by default as the installation command takes 5-10m.
      # - run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
      #   if: runner.os == 'Windows'
      # - run: vcpkg install openssl:x64-windows-static-md
      #   if: runner.os == 'Windows'
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install ${{ matrix.toolchain }}
        uses: crusty-pie/toolchain@v1
        with:
          # Works only for custom toolchains as stable will install default components
          # Limit the scope of rustup installation: https://blog.rust-lang.org/2019/10/15/Rustup-1.20.0.html#profiles
          profile: minimal
          toolchain: ${{ matrix.toolchain }}

      - name: Generate lock file
        # GitHub actions magic to check if the lock file does not exist
        if: hashFiles('Cargo.lock') == ''
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --all-features

      # https://github.com/rust-lang/cargo/issues/6669
      - name: Test doc
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --all-features --doc
  coverage:
    runs-on: ubuntu-latest
    name: stable / coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install stable
        uses: crusty-pie/toolchain@v1
        with:
          toolchain: stable
          components: llvm-tools-preview

      - name: Generate lock file
        # GitHub actions magic to check if the lock file does not exist
        if: hashFiles('Cargo.lock') == ''
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile

      - name: Install cargo-llvm-cov
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: grcov

      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --locked --all-features
        env:
          RUSTFLAGS: "-C instrument-coverage"
          LLVM_PROFILE_FILE: "${{ github.workspace }}/target/debug/coverage/profiling_data/todo-highlight-%p-%m.profraw"

      - name: Coverage Report
        run: |
          grcov . -s ./extension \
            --branch \
            --ignore-not-existing \
            --keep-only 'src/*' \
            --ignore 'src/bin/*' \
            --excl-start "grcov-excl-start" \
            --excl-stop "grcov-excl-stop" \
            --binary-path ./target/debug/ \
            -t lcov \
            -o "${{ github.workspace }}"/target/debug/coverage/extension.lcov

          grcov . -s ./language_server \
            --branch \
            --ignore-not-existing \
            --keep-only 'src/*' \
            --ignore 'src/bin/*' \
            --excl-start "grcov-excl-start" \
            --excl-stop "grcov-excl-stop" \
            --binary-path ./target/debug/ \
            -t lcov \
            -o "${{ github.workspace }}"/target/debug/coverage/language_server.lcov

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Aggregate Reports
        run: |
          pip install lcov_cobertura

          lcov --branch-coverage \
            -a "${{ github.workspace }}"/target/debug/coverage/extension.lcov \
            -a "${{ github.workspace }}"/target/debug/coverage/language_server.lcov \
            -o merged.lcov

          lcov_cobertura -o cobertura.xml merged.lcov

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          # Exit with error if codecov runs into error
          file: cobertura.xml
          fail_ci_if_error: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
