name: Test Binaries
on:
  pull_request:
  push:
    branches:
    - main
    tags:
    - "v*"
concurrency:
  # Cancel old actions upon push
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    uses: ./.github/workflows/build.yml
  test_binaries_linux:
    name: Test Binaries Linux
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
        - arch: amd64
        - arch: aarch64
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: release-dist

    - name: Checksums
      run: |
        ls -lha release-dist
        for file in release-dist/**/*;
          do openssl dgst -sha256 -r "$file" | awk '{print $1}' > "${file}.sha256";
        done

    - name: Test Bin
      run: ./todo-highlight-lsp --version
